# Generated by Django 5.2.3 on 2025-07-02 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=100)),
                ('bpm', models.PositiveIntegerField()),
                ('scale', models.CharField(max_length=50)),
                ('cover_art', models.ImageField(upload_to='covers/')),
                ('snippet_mp3', models.FileField(upload_to='snippets/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('wav_file', models.FileField(blank=True, null=True, upload_to='downloads/wav/')),
                ('wav_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('mp3_file', models.FileField(blank=True, null=True, upload_to='downloads/mp3/')),
                ('mp3_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('stems_file', models.FileField(blank=True, null=True, upload_to='downloads/stems/')),
                ('stems_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
