# Generated by Django 5.0.8 on 2026-01-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0006_make_cover_art_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
