# Generated by Django 5.0.8 on 2026-01-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0007_userprofile_middle_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='mp3_file',
            field=models.FileField(blank=True, null=True, upload_to='beats/'),
        ),
        migrations.AlterField(
            model_name='beat',
            name='snippet_mp3',
            field=models.FileField(blank=True, null=True, upload_to='mp3-snippets/'),
        ),
        migrations.AlterField(
            model_name='beat',
            name='stems_file',
            field=models.FileField(blank=True, null=True, upload_to='beats/'),
        ),
        migrations.AlterField(
            model_name='beat',
            name='wav_file',
            field=models.FileField(blank=True, null=True, upload_to='beats/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user-avatar/'),
        ),
    ]
