# Generated by Django 5.0.8 on 2026-01-19 23:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0010_beat_uploaded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beat',
            name='price',
        ),
        migrations.AlterField(
            model_name='beat',
            name='mp3_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='beats/'),
            preserve_default=False,
        ),
    ]
